name: Multi-Platform Build & Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'  # 触发条件：推送 v 开头的标签 (如 v1.0.0)

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.22.2

      - name: Build Android APK
        run: |
          flutter build apk --release
          # 重命名 APK 文件
          mv build/app/outputs/apk/release/app-release.apk DSTwok_android_${{ github.ref_name }}.apk

      - uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: DSTwok_android_${{ github.ref_name }}.apk

  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.22.2

      - name: Install CocoaPods
        run: |
          cd ios
          sudo gem install cocoapods
          pod install --repo-update

      - name: Build unsigned IPA
        run: |
          flutter build ipa --release --no-codesign
          # 重命名 IPA 文件
          mv build/ios/ipa/Runner.ipa DSTwok_ios_${{ github.ref_name }}.ipa

      - uses: actions/upload-artifact@v3
        with:
          name: ios-ipa
          path: DSTwok_ios_${{ github.ref_name }}.ipa

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.22.2

      - name: Build Windows
        run: |
          flutter build windows --release
          # 压缩文件并重命名
          cd build/windows/runner/Release
          ren DSTwok.exe DSTwok_${{ github.ref_name }}.exe
          7z a DSTwok_windows_${{ github.ref_name }}.zip ./*

      - uses: actions/upload-artifact@v3
        with:
          name: windows-exe
          path: build/windows/runner/Release/DSTwok_windows_${{ github.ref_name }}.zip

  create-release:
    runs-on: ubuntu-latest
    needs: [build-android, build-ios, build-windows]
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: DSTwok ${{ github.ref_name }}
          body: |
            ### Multi-Platform Release
            - Android: DSTwok_android_${{ github.ref_name }}.apk
            - iOS (Unsigned): DSTwok_ios_${{ github.ref_name }}.ipa
            - Windows: DSTwok_windows_${{ github.ref_name }}.zip
          files: |
            artifacts/android-apk/DSTwok_android_${{ github.ref_name }}.apk
            artifacts/ios-ipa/DSTwok_ios_${{ github.ref_name }}.ipa
            artifacts/windows-exe/DSTwok_windows_${{ github.ref_name }}.zip
