name: Multi-Platform Build & Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'  # 匹配语义化版本标签，如 v1.0.0

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract Version
        id: extract-version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          accept-licenses: true
          components: |
            ndk;29.0.13113456
            cmake;3.22.1

      - name: Build Android APK
        run: |
          flutter build apk --release
          mv build/app/outputs/apk/release/app-release.apk "dstwok_android_${{ steps.extract-version.outputs.version }}.apk"

      - uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: "dstwok_android_${{ steps.extract-version.outputs.version }}.apk"

  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract Version
        id: extract-version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
      - run: flutter pub get

      - run: pod repo update
        working-directory: ios

      - run: flutter build ios --release --no-codesign

      - name: Package IPA
        run: |
          cd build/ios/iphoneos
          mkdir Payload
          mv Runner.app Payload/
          zip -qr "dstwok_ios_${{ steps.extract-version.outputs.version }}.ipa" Payload

      - uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: "build/ios/iphoneos/dstwok_ios_${{ steps.extract-version.outputs.version }}.ipa"

  create-release:
    runs-on: ubuntu-latest
    needs: [build-android, build-ios]
    steps:
      - name: Extract Version
        id: extract-version  # 👈 必须在此作业中重新提取版本号
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - uses: actions/download-artifact@v4
        with:
          path: artifacts
          pattern: '*-apk,*-ipa'  # 👈 明确指定下载模式

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: dstwok ${{ github.ref_name }}
          body: |
            ### Multi-Platform Release
            - Android: [dstwok_android_${{ steps.extract-version.outputs.version }}.apk](dstwok_android_${{ steps.extract-version.outputs.version }}.apk)
            - iOS (Unsigned): [dstwok_ios_${{ steps.extract-version.outputs.version }}.ipa](dstwok_ios_${{ steps.extract-version.outputs.version }}.ipa)
          files: |
            artifacts/android-apk/dstwok_android_${{ steps.extract-version.outputs.version }}.apk
            artifacts/ios-ipa/dstwok_ios_${{ steps.extract-version.outputs.version }}.ipa
